// <auto-generated />
using JongBrabant.Kantinescherm.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JongBrabant.Kantinescherm.Migrations
{
    [DbContext(typeof(PriceListContext))]
    [Migration("20220902121413_AddOrder")]
    partial class AddOrder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JongBrabant.Kantinescherm.Models.GroupEntry", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"), 1L, 1);

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            GroupName = "Drank",
                            Order = 0
                        },
                        new
                        {
                            GroupId = 2,
                            GroupName = "Broodjes",
                            Order = 0
                        });
                });

            modelBuilder.Entity("JongBrabant.Kantinescherm.Models.ProductEntry", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("GroupId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            GroupId = 1,
                            Name = "Coca Cola",
                            Order = 0,
                            Price = 1.8m
                        },
                        new
                        {
                            ProductId = 2,
                            GroupId = 1,
                            Name = "Fanta",
                            Order = 0,
                            Price = 1.8m
                        },
                        new
                        {
                            ProductId = 3,
                            GroupId = 2,
                            Name = "Kroket",
                            Order = 0,
                            Price = 2.1m
                        },
                        new
                        {
                            ProductId = 4,
                            GroupId = 2,
                            Name = "Frikadel",
                            Order = 0,
                            Price = 2.10m
                        },
                        new
                        {
                            ProductId = 5,
                            GroupId = 2,
                            Name = "Jong Brabant",
                            Order = 0,
                            Price = 3.5m
                        });
                });

            modelBuilder.Entity("JongBrabant.Kantinescherm.Models.ProductEntry", b =>
                {
                    b.HasOne("JongBrabant.Kantinescherm.Models.GroupEntry", "Group")
                        .WithMany("Prices")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("JongBrabant.Kantinescherm.Models.GroupEntry", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
