// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shabroek.Kantinescherm.API.Model;

#nullable disable

namespace Shabroek.Kantinescherm.API.Migrations
{
    [DbContext(typeof(PriceListContext))]
    partial class PriceListContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Shabroek.Kantinescherm.API.Model.GroupEntry", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"), 1L, 1);

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            GroupName = "Drank"
                        },
                        new
                        {
                            GroupId = 2,
                            GroupName = "Broodjes"
                        });
                });

            modelBuilder.Entity("Shabroek.Kantinescherm.API.Model.PriceEntry", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceId"), 1L, 1);

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PriceId");

                    b.HasIndex("GroupId");

                    b.ToTable("Prices");

                    b.HasData(
                        new
                        {
                            PriceId = 1,
                            GroupId = 1,
                            Name = "Coca Cola",
                            Price = 1.8m
                        },
                        new
                        {
                            PriceId = 2,
                            GroupId = 1,
                            Name = "Fanta",
                            Price = 1.8m
                        },
                        new
                        {
                            PriceId = 3,
                            GroupId = 2,
                            Name = "Kroket",
                            Price = 2.1m
                        },
                        new
                        {
                            PriceId = 4,
                            GroupId = 2,
                            Name = "Frikadel",
                            Price = 2.10m
                        },
                        new
                        {
                            PriceId = 5,
                            GroupId = 2,
                            Name = "Jong Brabant",
                            Price = 3.5m
                        });
                });

            modelBuilder.Entity("Shabroek.Kantinescherm.API.Model.PriceEntry", b =>
                {
                    b.HasOne("Shabroek.Kantinescherm.API.Model.GroupEntry", "Group")
                        .WithMany("Prices")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Shabroek.Kantinescherm.API.Model.GroupEntry", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
